//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionGeneral.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int idChat { get; set; }
        public int numeroChat { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string numeroLicencia { get; set; }
        public Nullable<int> idMensaje { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Mensaje Mensaje { get; set; }
    }
}
