//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionGeneral.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delegacion()
        {
            this.Reporte = new HashSet<Reporte>();
        }
    
        public int idDelegacion { get; set; }
        public int numeroDelegacion { get; set; }
        public string nombre { get; set; }
        public string colonia { get; set; }
        public string codigoPostal { get; set; }
        public string municipio { get; set; }
        public string telefono { get; set; }
        public string correoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte> Reporte { get; set; }
    }
}
