//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionGeneral.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_Vehiculo
    {
        public int idReporte_Vehiculo { get; set; }
        public Nullable<int> idVehiculo { get; set; }
        public Nullable<int> idReporte { get; set; }
    
        public virtual Reporte Reporte { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
