//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionGeneral.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reporte()
        {
            this.Reporte_Vehiculo = new HashSet<Reporte_Vehiculo>();
        }
    
        public int idReporte { get; set; }
        public int numeroReporte { get; set; }
        public string estatus { get; set; }
        public Nullable<int> numeroDelegacion { get; set; }
        public Nullable<int> folioDictamen { get; set; }
    
        public virtual Delegacion Delegacion { get; set; }
        public virtual Dictamen Dictamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte_Vehiculo> Reporte_Vehiculo { get; set; }
    }
}
